### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by argilo**
In case you'd like to add CI to the project, I've created a basic GitHub Actions workflow here. It verifies that the build and install succeeds when using each of the three Makefile variants.

If desired, additional test steps could be added.

The output of a sample run on my fork can be seen here: https://github.com/argilo/ka9q-radio/actions/runs/2301026546

### CODE REVIEW

**Comment by ka9q** [comment]
I don't know what that means, but if it doesn't interfere with anything I'm doing I'm OK with it.

**Comment by ka9q** [comment]
I notice you're using 'brew' on MacOS. I use 'port'. Is there any meaningful difference?

**Comment by argilo** [comment]
Basically it means that every time a commit is pushed to GitHub, or a pull request is opened, GitHub will spin up containers and build the project, verifying that no new compile errors have been introduced. GitHub will show a green check mark next to the commit if the builds succeed. It shouldn't interfere with your work, but may alert you to bugs.

I used brew because it is available by default on GitHub's build machines, while port is not.

**Comment by ka9q** [comment]
I didn't even know that Github could do this, but as long as it doesn't interfere with anything I have no objection. And if their compilers spot problems that mine don't, this could be helpful.

**Comment by ka9q** [comment]
I've been doing frequent commits of small changes, would this create a problem?

**Comment by argilo** [comment]
That shouldn't be a problem. If a lot of commits are pushed around the same time, GitHub simply queues up the builds. In that event, it will just take a bit longer to see whether a given commit passed or failed.

**Comment by argilo** [comment]
At the moment, the execution time is approximately 1 minute for the Linux builds, and 5 minutes for the MacOS build. (MacOS takes a bit longer because avahi must be built from source; it's not available as a brew package.)

**Comment by ka9q** [comment]
So is there any downside to my accepting this pull request?

**Comment by argilo** [comment]
I don't see any downside.

If it doesn't work out and you want to get rid of it, all you have to do is delete the `.github` folder.

**Comment by argilo** [comment]
At the moment, this just verifies that `make` and `sudo make install` execute without errors on Ubuntu and macOS. It could certainly be extended to test other things. GitHub actions runs arbitrary shell commands, so we could ask it to run the executables once they're built, run a test suite, or even produce a pre-packaged version of the software for download.

**Comment by ka9q** [comment]
I guess we could write some test programs. Send commands to a radiod or airspyd instance, see if they get the expected result. Unit tests are a good idea anyway.

**Pull request merged**
